### ISSUE TITLE
Buy a domain and a SMS subscription

### ISSUE THREAD

**Issue by cxm0000** [AdamGustavsson/KalasServerless#19]

**Comment by AdamGustavsson** [comment]
I bought a Hallon.se subscription today. I expect the sim card to arrive in the next couple of days

**Comment by cxm0000** [comment]
excellent! should I buy a domain? what shall we call it?

**Comment by AdamGustavsson** [comment]
Kalas.io är ledig. Den funkar tycker jag.

**Comment by cxm0000** [comment]
köpte! vi behöver en server då. Har du bra koll på hur mycket kostar AWS?

**Comment by AdamGustavsson** [comment]
Här står hur man sätter upp s3 med egen domän:
http://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html

Jag har Aws gratis i ett år. Om vi inte får mycket trafik. Men jag tror inte det blir dyrt.
