### ISSUE TITLE
Translate the site

### ISSUE THREAD

**Issue by AdamGustavsson** [AdamGustavsson/KalasServerless#22]
We can probably use:
https://www.npmjs.com/package/i18n

**Comment by cxm0000** [comment]
https://www.npmjs.com/package/redux-i18n seems to be easy and good enough

**Comment by cxm0000** [comment]
Implemented https://www.npmjs.com/package/react-redux-i18n. you could find examples there. The only thing to do is go into "client/src" and do a "npm isntall".
